apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
  # Optional: add this annotation if you want the Kustomization patch (in your Spec.Patches) to target it.
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  targetNamespace: ingress
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
   values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
