apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.14.0"  # set a known-good version; update when needed
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: ingress
  values:
    controller:
      replicaCount: 2
      updateStrategy:
        type: RollingUpdate
      service:
        type: LoadBalancer
        annotations: {}
        # If on AKS/ACS and you want a specific LB, add cloud annotations here.
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true  # requires Prometheus Operator CRDs if you use ServiceMonitor
      admissionWebhooks:
        enabled: true
      watchIngressWithoutClass: true
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
      extraArgs:
        default-ssl-certificate: ""
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    # Optional node constraints
    # nodeSelector:
    #   kubernetes.io/os: linux
    # tolerations:
    #   - key: "node-role.kubernetes.io/control-plane"
    #     effect: "NoSchedule"
    #     operator: "
