apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 15m
  releaseName: ingress-nginx  # Ensures consistent release name
  chart:
    spec:
      chart: ingress-nginx
      version: "4.14.0"  # Known-good version
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true
    replace: true  # Force install if previous release is missing
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  targetNamespace: ingress
  values:
    controller:
      replicaCount: 2
      updateStrategy:
        type: RollingUpdate
      service:
        type: LoadBalancer
        annotations: {}
      admissionWebhooks:
        enabled: true
      watchIngressWithoutClass: true
      ingressClassResource:
        name: nginx
        enabled: true
        default: true
      config:
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
      extraArgs:
        default-ssl-certificate: ""
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512
