apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system        # HelmRelease stays in flux-system (Flux controllers watch here)
spec:
  interval: 5m
  targetNamespace: ingress      # ✅ This is where the chart will be installed
  chart:
    spec:
      chart: ingress-nginx
      version: "4.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    createNamespace: true       # ✅ Creates the ingress namespace if missing
  values:
       controller:
      replicaCount: 1
      service:
